# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58b15f5dcf0025cdc659f12c167b0008ecf422c4d99e62f33e65b27a5172c7b0f4b41f9a5de7e3f7d8e15153b2211485ddee9a6eb04d37c945f6c094b50baea7

test:
  secret_key_base: 5f0cdd21641e1e2b48df499de7cc17673fec2a16aa3db56b08b9cb7c559a4578a80035fe7526fe4a56ef9a2795366d308cfa9c33a7a0149959d1ad74c699a10c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: b8d319395ae98c61936b0e8395d9bed9c50bdeaa0dd1ae7856f80f7b1a9c58248c756cd67df51fd5d9eba31f32fb0869d2eeb25272c3079ad690741bb1bfd74f
